
This is the source repository for destributing CAP, Component Abstraction
Planner, in [[http://guicho271828.github.io/publications/icaps15-submission7.pdf][Asai, M.; Fukunaga, A: 2015. Solving Large Scale Planning
Problems with Component Macros. In ICAPS2015]].

* Building

Simply run =make= to make an executable binary =componen-planner=.

* Dependency

+ https://github.com/roswell/roswell
+ =cgroup-bin= Restart is required after the installation (in order to make cgroups activated).
+ =libffi=

:  sudo apt-get install cgroup-bin libffi-dev git make autoconf build-essential libtool libglib2.0-dev 

Also, the [[http://www.fast-downward.org/ObtainingAndRunningFastDownward][dependencies of Fast Downward]] should be resolved. It is:

:  sudo apt-get install mercurial g++ make python flex bison g++-multilib

We do not support 32bit systems.
When MainPlanner/ComponentPlanner uses 32bit planners such as marvin,
install the 32bit library. The list is not comprehensive.

:  sudo apt-get install ia32-libs

* Running

Command line options are available by running =componen-planner= with no
arguments.

* Testing

Test instances are in test.tar.gz, so unpack it accordingly.

test.sh is a +simple+ shell script that tests if the binary works correctly
on a small problem set.
